### ISSUE TITLE
Just looking

### ISSUE THREAD

**Issue by brandonparsons** [stevedomin/backstage#4]
Hi there, just poking around!

Wondering when it would make sense to use this, versus a Redis-backed queuing library like `exq` or `toniq`?

**Comment by stevedomin** [comment]
Hi @brandonparsons 

Couple of reasons:

* Maybe you are already using Postgres and don't want to use/maintain another datastore.
* Transactional enqueuing: you want to enqueue job alongside other changes in your database. Let's say you have a database transaction where you can a couple of records as well as enqueuing a job that communicates with an external provider. With redis, if for some reason the transaction fails after you have enqueued the job then the job will be performed anyway. Whereas with backstage the transaction would be rolled back (including the job being stored in the database).
* Reliability: once a job is committed to the database you can safely assume you won't lose it.

**Comment by brandonparsons** [comment]
Thanks for the input :)

**Comment by stevedomin** [comment]
You're welcome, let me know if you have other questions!
